### ISSUE TITLE
你好，大神请问a40l i5需要用哪一个efi?

### ISSUE THREAD

**Issue by zhengdaoyi** [i0Ek3/Funny-ianpasm#1]
需要改cpu的ssdt吗？

**Comment by i0Ek3** [comment]
@zhengdaoyi 这里我没有提供i5的，你可以关注原作者@ym2008的帖子 http://bbs.pcbeta.com/viewthread-1761222-1-1.html。

**Comment by zhengdaoyi** [comment]
谢谢大神，可以装上，不过重启之后进不去系统了，进度条跑完就卡住了

**Comment by zhengdaoyi** [comment]
大神谢谢！我是用lastest直接就可以用了，重启都行了，扬声器睡眠后正常，i5可用。后面v1之后的版本可能用的方法不对各种都有出现花屏。不过之后版本clover主题好看！再次感谢！
